
export const ADD_BRAND = "ADD_BRAND";
export const FETCH_BRANDS = "FETCH_BRAND";
export const RECEIVED_BRANDS = "RECEIVED_BRAND";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCT";
export const RECEIVED_PRODUCTS = "RECEIVED_PRODUCT";

export const ADD_DISTRIBUTOR = "ADD_DISTRIBUTOR";
export const FETCH_DISTRIBUTORS = "FETCH_DISTRIBUTOR";
export const RECEIVED_DISTRIBUTORS = "RECEIVED_DISTRIBUTOR";

export const ADD_FIELDFORCE = "ADD_FIELDFORCE";
export const FETCH_FIELDFORCES = "FETCH_FIELDFORCE";
export const RECEIVED_FIELDFORCES = "RECEIVED_FIELDFORCE";

export const ADD_MARKET = "ADD_MARKET";
export const FETCH_MARKETS = "FETCH_MARKET";
export const RECEIVED_MARKETS = "RECEIVED_MARKET";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const NETWORK_CALL_START = "NETWORK_CALL_START";
export const NETWORK_CALL_END = "NETWORK_CALL_END";
export const NETWORK_CALL_ERROR = "NETWORK_CALL_ERROR";